# Generated by Django 5.0.7 on 2026-10-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReglagesClinique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_clinique",
                    models.CharField(
                        default="Parcelles Véto",
                        max_length=120,
                        verbose_name="Nom de la clinique",
                    ),
                ),
                (
                    "sous_titre",
                    models.CharField(
                        blank=True,
                        default="Cabinet de soins vétérinaires",
                        max_length=150,
                        verbose_name="Sous-titre",
                    ),
                ),
                (
                    "nom_veterinaire",
                    models.CharField(
                        blank=True,
                        default="Dr Ibrahima Pierre GUISSE",
                        max_length=120,
                        verbose_name="Vétérinaire",
                    ),
                ),
                (
                    "adresse",
                    models.CharField(
                        blank=True,
                        default="Thiès, Parcelles Assainies U2",
                        max_length=200,
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "repere",
                    models.CharField(
                        blank=True,
                        default="En face du cimetière de Keur Dago",
                        max_length=200,
                        verbose_name="Repère",
                    ),
                ),
                (
                    "telephones",
                    models.CharField(
                        blank=True,
                        default="77 538 57 29 / 76 833 16 23",
                        max_length=120,
                        verbose_name="Téléphones",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        default="parcelles-veto@gmail.com",
                        max_length=120,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "slogan",
                    models.CharField(
                        blank=True,
                        default="La santé animale, notre priorité.",
                        max_length=150,
                        verbose_name="Slogan",
                    ),
                ),
                ("logo", models.BinaryField(blank=True, null=True)),
                (
                    "logo_version",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "mention_ordonnance",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Mention en bas des ordonnances",
                    ),
                ),
                (
                    "seuil_alerte_defaut",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Seuil d'alerte par défaut"
                    ),
                ),
                (
                    "notif_consultation_nouvelle",
                    models.BooleanField(
                        default=True, verbose_name="Nouvelle consultation"
                    ),
                ),
                (
                    "notif_consultation_cloturee",
                    models.BooleanField(
                        default=True, verbose_name="Consultation clôturée"
                    ),
                ),
                (
                    "notif_rdv",
                    models.BooleanField(
                        default=True, verbose_name="Nouveau rendez-vous"
                    ),
                ),
                (
                    "notif_vente",
                    models.BooleanField(
                        default=True, verbose_name="Vente / opération en pharmacie"
                    ),
                ),
                (
                    "notif_stock",
                    models.BooleanField(
                        default=True, verbose_name="Alerte de stock bas"
                    ),
                ),
                ("modifie_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Réglages de la clinique",
                "verbose_name_plural": "Réglages de la clinique",
            },
        ),
    ]
