# Generated by Django 5.0.7 on 2026-10-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reglagesclinique",
            name="notif_compte",
            field=models.BooleanField(
                default=True, verbose_name="Changement de mot de passe"
            ),
        ),
    ]
