# Generated by Django 5.0.7 on 2026-09-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(default='Inconnu', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
