# Generated by Django 5.0.7 on 2026-09-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('DOCTEUR', 'Docteur Vétérinaire'), ('EMPLOYE', 'Employé / Assistant')], default='EMPLOYE', max_length=20),
        ),
    ]
