# Generated by Django 6.1.1 on 2026-09-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(blank=True, choices=[('DOCTEUR', 'Docteur Vétérinaire'), ('ASSISTANT', 'Employé / Assistant'), ('PHARMACIEN', 'Pharmacien')], max_length=20, null=True),
        ),
    ]
