# Generated by Django 5.0.7 on 2026-10-09 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_role_employe_vers_assistant"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="mdp_change_le",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Mot de passe changé le"
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="mdp_change_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mot de passe changé par",
            ),
        ),
    ]
