# Generated by Django 5.0.7 on 2026-09-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_id_alter_ligneordonnance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='client_nouveau',
            field=models.BooleanField(default=False, verbose_name='Client nouvellement créé'),
        ),
    ]
