# Generated by Django 6.1.1 on 2026-09-21 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_alter_consultation_id_alter_ligneordonnance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='consultation_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_suivants', to='consultations.consultation'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='type_rdv',
            field=models.CharField(choices=[('CABINET', 'Cabinet'), ('DOMICILE', 'Domicile')], default='CABINET', max_length=20),
        ),
        migrations.AlterField(
            model_name='rendezvousmanuel',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
