# Generated by Django 6.0.6 on 2026-06-29 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('espece', models.CharField(max_length=100)),
                ('race', models.CharField(blank=True, max_length=100, null=True)),
                ('sexe', models.CharField(blank=True, max_length=10, null=True)),
                ('poids', models.FloatField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animaux', to='clients.client')),
            ],
        ),
    ]
