# Generated by Django 5.0.7 on 2026-10-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type_action",
            field=models.CharField(
                choices=[
                    ("vente", "Vente"),
                    ("consultation", "Consultation"),
                    ("stock", "Alerte Stock"),
                    ("rdv", "Rendez-vous"),
                    ("compte", "Compte utilisateur"),
                ],
                default="vente",
                max_length=50,
            ),
        ),
    ]
